### ISSUE TITLE
Molasses wipe-off after completing Benbow doesn't work

### ISSUE THREAD

**Issue by elasota** [elasota/mti-bugs#3]

**Comment by Thunderforge** [comment]
I was able to reproduce this too. The screen is completely clear and a sponge appears in the upper right corner.

![Molasses Wipe Off](https://github.com/elasota/mti-bugs/assets/6200170/bd027e7e-83ef-44be-a799-4d563a971991)

You still have to drag the sponge around till it has touched about 60% of the screen (which is normal behavior), at which point the game continues.

**Comment by elasota** [comment]
Fixed
